//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COREAndroid.wsDispositivo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IwsDispositivo", Namespace="http://tempuri.org/")]
    public partial class wsDispositivo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarDispositivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarDispositivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarDispositivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaDispositivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarDispositivoCuadrilleroOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarDispositivoCuadrilleroOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaDispositivoCuadrilleroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaTiempoReportarseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardaUbicacionOperationCompleted;
        
        /// <remarks/>
        public wsDispositivo() {
            this.Url = "http://207.248.58.245:90/RACE.Services/wsDispositivo.svc";
        }
        
        public wsDispositivo(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        public event BuscarDispositivoCompletedEventHandler BuscarDispositivoCompleted;
        
        /// <remarks/>
        public event GuardarDispositivoCompletedEventHandler GuardarDispositivoCompleted;
        
        /// <remarks/>
        public event EditarDispositivoCompletedEventHandler EditarDispositivoCompleted;
        
        /// <remarks/>
        public event BajaDispositivoCompletedEventHandler BajaDispositivoCompleted;
        
        /// <remarks/>
        public event BuscarDispositivoCuadrilleroCompletedEventHandler BuscarDispositivoCuadrilleroCompleted;
        
        /// <remarks/>
        public event GuardarDispositivoCuadrilleroCompletedEventHandler GuardarDispositivoCuadrilleroCompleted;
        
        /// <remarks/>
        public event BajaDispositivoCuadrilleroCompletedEventHandler BajaDispositivoCuadrilleroCompleted;
        
        /// <remarks/>
        public event ConsultaTiempoReportarseCompletedEventHandler ConsultaTiempoReportarseCompleted;
        
        /// <remarks/>
        public event GuardaUbicacionCompletedEventHandler GuardaUbicacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwsDispositivo/BuscarDispositivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CapaEntidad")]
        public Dispositivo[] BuscarDispositivo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Dispositivo Dispositivo, bool Disp_Activo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Disp_ActivoSpecified) {
            object[] results = this.Invoke("BuscarDispositivo", new object[] {
                        Dispositivo,
                        Disp_Activo,
                        Disp_ActivoSpecified});
            return ((Dispositivo[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarDispositivoAsync(Dispositivo Dispositivo, bool Disp_Activo, bool Disp_ActivoSpecified) {
            this.BuscarDispositivoAsync(Dispositivo, Disp_Activo, Disp_ActivoSpecified, null);
        }
        
        /// <remarks/>
        public void BuscarDispositivoAsync(Dispositivo Dispositivo, bool Disp_Activo, bool Disp_ActivoSpecified, object userState) {
            if ((this.BuscarDispositivoOperationCompleted == null)) {
                this.BuscarDispositivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarDispositivoOperationCompleted);
            }
            this.InvokeAsync("BuscarDispositivo", new object[] {
                        Dispositivo,
                        Disp_Activo,
                        Disp_ActivoSpecified}, this.BuscarDispositivoOperationCompleted, userState);
        }
        
        private void OnBuscarDispositivoOperationCompleted(object arg) {
            if ((this.BuscarDispositivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarDispositivoCompleted(this, new BuscarDispositivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwsDispositivo/GuardarDispositivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dispositivo GuardarDispositivo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Dispositivo Dispositivo) {
            object[] results = this.Invoke("GuardarDispositivo", new object[] {
                        Dispositivo});
            return ((Dispositivo)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarDispositivoAsync(Dispositivo Dispositivo) {
            this.GuardarDispositivoAsync(Dispositivo, null);
        }
        
        /// <remarks/>
        public void GuardarDispositivoAsync(Dispositivo Dispositivo, object userState) {
            if ((this.GuardarDispositivoOperationCompleted == null)) {
                this.GuardarDispositivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarDispositivoOperationCompleted);
            }
            this.InvokeAsync("GuardarDispositivo", new object[] {
                        Dispositivo}, this.GuardarDispositivoOperationCompleted, userState);
        }
        
        private void OnGuardarDispositivoOperationCompleted(object arg) {
            if ((this.GuardarDispositivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarDispositivoCompleted(this, new GuardarDispositivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwsDispositivo/EditarDispositivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EditarDispositivo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Dispositivo Dispositivo, out int EditarDispositivoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool EditarDispositivoResultSpecified) {
            object[] results = this.Invoke("EditarDispositivo", new object[] {
                        Dispositivo});
            EditarDispositivoResult = ((int)(results[0]));
            EditarDispositivoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void EditarDispositivoAsync(Dispositivo Dispositivo) {
            this.EditarDispositivoAsync(Dispositivo, null);
        }
        
        /// <remarks/>
        public void EditarDispositivoAsync(Dispositivo Dispositivo, object userState) {
            if ((this.EditarDispositivoOperationCompleted == null)) {
                this.EditarDispositivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarDispositivoOperationCompleted);
            }
            this.InvokeAsync("EditarDispositivo", new object[] {
                        Dispositivo}, this.EditarDispositivoOperationCompleted, userState);
        }
        
        private void OnEditarDispositivoOperationCompleted(object arg) {
            if ((this.EditarDispositivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarDispositivoCompleted(this, new EditarDispositivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwsDispositivo/BajaDispositivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaDispositivo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Id_DispStr, int Disp_Id_UMod, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Disp_Id_UModSpecified, out int BajaDispositivoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool BajaDispositivoResultSpecified) {
            object[] results = this.Invoke("BajaDispositivo", new object[] {
                        Id_DispStr,
                        Disp_Id_UMod,
                        Disp_Id_UModSpecified});
            BajaDispositivoResult = ((int)(results[0]));
            BajaDispositivoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void BajaDispositivoAsync(string Id_DispStr, int Disp_Id_UMod, bool Disp_Id_UModSpecified) {
            this.BajaDispositivoAsync(Id_DispStr, Disp_Id_UMod, Disp_Id_UModSpecified, null);
        }
        
        /// <remarks/>
        public void BajaDispositivoAsync(string Id_DispStr, int Disp_Id_UMod, bool Disp_Id_UModSpecified, object userState) {
            if ((this.BajaDispositivoOperationCompleted == null)) {
                this.BajaDispositivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaDispositivoOperationCompleted);
            }
            this.InvokeAsync("BajaDispositivo", new object[] {
                        Id_DispStr,
                        Disp_Id_UMod,
                        Disp_Id_UModSpecified}, this.BajaDispositivoOperationCompleted, userState);
        }
        
        private void OnBajaDispositivoOperationCompleted(object arg) {
            if ((this.BajaDispositivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaDispositivoCompleted(this, new BajaDispositivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwsDispositivo/BuscarDispositivoCuadrillero", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CapaEntidad")]
        public Dispositivo[] BuscarDispositivoCuadrillero(int Id_Disp, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_DispSpecified) {
            object[] results = this.Invoke("BuscarDispositivoCuadrillero", new object[] {
                        Id_Disp,
                        Id_DispSpecified});
            return ((Dispositivo[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarDispositivoCuadrilleroAsync(int Id_Disp, bool Id_DispSpecified) {
            this.BuscarDispositivoCuadrilleroAsync(Id_Disp, Id_DispSpecified, null);
        }
        
        /// <remarks/>
        public void BuscarDispositivoCuadrilleroAsync(int Id_Disp, bool Id_DispSpecified, object userState) {
            if ((this.BuscarDispositivoCuadrilleroOperationCompleted == null)) {
                this.BuscarDispositivoCuadrilleroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarDispositivoCuadrilleroOperationCompleted);
            }
            this.InvokeAsync("BuscarDispositivoCuadrillero", new object[] {
                        Id_Disp,
                        Id_DispSpecified}, this.BuscarDispositivoCuadrilleroOperationCompleted, userState);
        }
        
        private void OnBuscarDispositivoCuadrilleroOperationCompleted(object arg) {
            if ((this.BuscarDispositivoCuadrilleroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarDispositivoCuadrilleroCompleted(this, new BuscarDispositivoCuadrilleroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwsDispositivo/GuardarDispositivoCuadrillero", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dispositivo GuardarDispositivoCuadrillero([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Dispositivo DispositivoCuadrillero) {
            object[] results = this.Invoke("GuardarDispositivoCuadrillero", new object[] {
                        DispositivoCuadrillero});
            return ((Dispositivo)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarDispositivoCuadrilleroAsync(Dispositivo DispositivoCuadrillero) {
            this.GuardarDispositivoCuadrilleroAsync(DispositivoCuadrillero, null);
        }
        
        /// <remarks/>
        public void GuardarDispositivoCuadrilleroAsync(Dispositivo DispositivoCuadrillero, object userState) {
            if ((this.GuardarDispositivoCuadrilleroOperationCompleted == null)) {
                this.GuardarDispositivoCuadrilleroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarDispositivoCuadrilleroOperationCompleted);
            }
            this.InvokeAsync("GuardarDispositivoCuadrillero", new object[] {
                        DispositivoCuadrillero}, this.GuardarDispositivoCuadrilleroOperationCompleted, userState);
        }
        
        private void OnGuardarDispositivoCuadrilleroOperationCompleted(object arg) {
            if ((this.GuardarDispositivoCuadrilleroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarDispositivoCuadrilleroCompleted(this, new GuardarDispositivoCuadrilleroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwsDispositivo/BajaDispositivoCuadrillero", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaDispositivoCuadrillero(int Id_DispCua, [System.Xml.Serialization.XmlIgnoreAttribute()] bool Id_DispCuaSpecified, int DispCua_Id_UMod, [System.Xml.Serialization.XmlIgnoreAttribute()] bool DispCua_Id_UModSpecified, out int BajaDispositivoCuadrilleroResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool BajaDispositivoCuadrilleroResultSpecified) {
            object[] results = this.Invoke("BajaDispositivoCuadrillero", new object[] {
                        Id_DispCua,
                        Id_DispCuaSpecified,
                        DispCua_Id_UMod,
                        DispCua_Id_UModSpecified});
            BajaDispositivoCuadrilleroResult = ((int)(results[0]));
            BajaDispositivoCuadrilleroResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void BajaDispositivoCuadrilleroAsync(int Id_DispCua, bool Id_DispCuaSpecified, int DispCua_Id_UMod, bool DispCua_Id_UModSpecified) {
            this.BajaDispositivoCuadrilleroAsync(Id_DispCua, Id_DispCuaSpecified, DispCua_Id_UMod, DispCua_Id_UModSpecified, null);
        }
        
        /// <remarks/>
        public void BajaDispositivoCuadrilleroAsync(int Id_DispCua, bool Id_DispCuaSpecified, int DispCua_Id_UMod, bool DispCua_Id_UModSpecified, object userState) {
            if ((this.BajaDispositivoCuadrilleroOperationCompleted == null)) {
                this.BajaDispositivoCuadrilleroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaDispositivoCuadrilleroOperationCompleted);
            }
            this.InvokeAsync("BajaDispositivoCuadrillero", new object[] {
                        Id_DispCua,
                        Id_DispCuaSpecified,
                        DispCua_Id_UMod,
                        DispCua_Id_UModSpecified}, this.BajaDispositivoCuadrilleroOperationCompleted, userState);
        }
        
        private void OnBajaDispositivoCuadrilleroOperationCompleted(object arg) {
            if ((this.BajaDispositivoCuadrilleroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaDispositivoCuadrilleroCompleted(this, new BajaDispositivoCuadrilleroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwsDispositivo/ConsultaTiempoReportarse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TiempoReportarse ConsultaTiempoReportarse([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string disp_numero) {
            object[] results = this.Invoke("ConsultaTiempoReportarse", new object[] {
                        disp_numero});
            return ((TiempoReportarse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaTiempoReportarseAsync(string disp_numero) {
            this.ConsultaTiempoReportarseAsync(disp_numero, null);
        }
        
        /// <remarks/>
        public void ConsultaTiempoReportarseAsync(string disp_numero, object userState) {
            if ((this.ConsultaTiempoReportarseOperationCompleted == null)) {
                this.ConsultaTiempoReportarseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaTiempoReportarseOperationCompleted);
            }
            this.InvokeAsync("ConsultaTiempoReportarse", new object[] {
                        disp_numero}, this.ConsultaTiempoReportarseOperationCompleted, userState);
        }
        
        private void OnConsultaTiempoReportarseOperationCompleted(object arg) {
            if ((this.ConsultaTiempoReportarseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaTiempoReportarseCompleted(this, new ConsultaTiempoReportarseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwsDispositivo/GuardaUbicacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardaUbicacion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DispositivoUbicacion ubicacion, out int GuardaUbicacionResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GuardaUbicacionResultSpecified) {
            object[] results = this.Invoke("GuardaUbicacion", new object[] {
                        ubicacion});
            GuardaUbicacionResult = ((int)(results[0]));
            GuardaUbicacionResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void GuardaUbicacionAsync(DispositivoUbicacion ubicacion) {
            this.GuardaUbicacionAsync(ubicacion, null);
        }
        
        /// <remarks/>
        public void GuardaUbicacionAsync(DispositivoUbicacion ubicacion, object userState) {
            if ((this.GuardaUbicacionOperationCompleted == null)) {
                this.GuardaUbicacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardaUbicacionOperationCompleted);
            }
            this.InvokeAsync("GuardaUbicacion", new object[] {
                        ubicacion}, this.GuardaUbicacionOperationCompleted, userState);
        }
        
        private void OnGuardaUbicacionOperationCompleted(object arg) {
            if ((this.GuardaUbicacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardaUbicacionCompleted(this, new GuardaUbicacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CapaEntidad")]
    public partial class Dispositivo {
        
        /// <comentarios/>
        public System.DateTime DispCua_FAsignacion;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DispCua_FAsignacionSpecified;
        
        /// <comentarios/>
        public System.DateTime DispCua_FDesAsignacion;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DispCua_FDesAsignacionSpecified;
        
        /// <comentarios/>
        public int DispCua_Id_UCreo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DispCua_Id_UCreoSpecified;
        
        /// <comentarios/>
        public int DispCua_Id_UMod;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DispCua_Id_UModSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DispCua_Nombre;
        
        /// <comentarios/>
        public bool Disp_Activo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Disp_ActivoSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Disp_ActivoStr;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Disp_IMEI;
        
        /// <comentarios/>
        public int Disp_Id_UCreo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Disp_Id_UCreoSpecified;
        
        /// <comentarios/>
        public int Disp_Id_UMod;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Disp_Id_UModSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Disp_Modelo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Disp_Numero;
        
        /// <comentarios/>
        public int Id_Cua;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_CuaSpecified;
        
        /// <comentarios/>
        public int Id_Disp;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_DispSpecified;
        
        /// <comentarios/>
        public int Id_DispCua;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_DispCuaSpecified;
        
        /// <comentarios/>
        public int Id_Reportarse;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_ReportarseSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id_ReportarseStr;
        
        /// <comentarios/>
        public int Id_Suc;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_SucSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id_SucStr;
        
        /// <comentarios/>
        public int Id_TAsignacion;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_TAsignacionSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id_TAsignacionStr;
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CapaEntidad")]
    public partial class DispositivoUbicacion {
        
        /// <comentarios/>
        public System.DateTime DispU_FCreo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DispU_FCreoSpecified;
        
        /// <comentarios/>
        public decimal DispU_Latitud;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DispU_LatitudSpecified;
        
        /// <comentarios/>
        public decimal DispU_Longitud;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DispU_LongitudSpecified;
        
        /// <comentarios/>
        public int Id_Cua;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_CuaSpecified;
        
        /// <comentarios/>
        public int Id_Disp;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_DispSpecified;
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CapaEntidad")]
    public partial class TiempoReportarse {
        
        /// <comentarios/>
        public int Id_Dispositivo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_DispositivoSpecified;
        
        /// <comentarios/>
        public int Id_Reportarse;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_ReportarseSpecified;
        
        /// <comentarios/>
        public bool Reportarse_Activo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reportarse_ActivoSpecified;
        
        /// <comentarios/>
        public int Reportarse_Tiempo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reportarse_TiempoSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reportarse_TiempoStr;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void BuscarDispositivoCompletedEventHandler(object sender, BuscarDispositivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarDispositivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarDispositivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Dispositivo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Dispositivo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GuardarDispositivoCompletedEventHandler(object sender, GuardarDispositivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarDispositivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarDispositivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Dispositivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Dispositivo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void EditarDispositivoCompletedEventHandler(object sender, EditarDispositivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditarDispositivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditarDispositivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int EditarDispositivoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool EditarDispositivoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void BajaDispositivoCompletedEventHandler(object sender, BajaDispositivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BajaDispositivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BajaDispositivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int BajaDispositivoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool BajaDispositivoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void BuscarDispositivoCuadrilleroCompletedEventHandler(object sender, BuscarDispositivoCuadrilleroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarDispositivoCuadrilleroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarDispositivoCuadrilleroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Dispositivo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Dispositivo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GuardarDispositivoCuadrilleroCompletedEventHandler(object sender, GuardarDispositivoCuadrilleroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarDispositivoCuadrilleroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarDispositivoCuadrilleroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Dispositivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Dispositivo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void BajaDispositivoCuadrilleroCompletedEventHandler(object sender, BajaDispositivoCuadrilleroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BajaDispositivoCuadrilleroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BajaDispositivoCuadrilleroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int BajaDispositivoCuadrilleroResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool BajaDispositivoCuadrilleroResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void ConsultaTiempoReportarseCompletedEventHandler(object sender, ConsultaTiempoReportarseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaTiempoReportarseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaTiempoReportarseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TiempoReportarse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TiempoReportarse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GuardaUbicacionCompletedEventHandler(object sender, GuardaUbicacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardaUbicacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardaUbicacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int GuardaUbicacionResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool GuardaUbicacionResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}
